# core/modules/activity_log/modul.yaml
label:       Activity Log
nav_group:   System
nav_default: false

card_actions:
  - type: info
    url: /ui/activity_log/{item}/detail
  - type: log
    url: /ui/activity_log/{item}/log
