fields:
  - type: section
    label: Allgemein
    cols: 1

  - key: extra_disks
    label: Zusätzlicher Speicher
    type: text
    description: "Pfad eines zusätzlichen Datenträgers -- von mirror, packages und sync zwingend benötigt, bei backup optional"
    mono: true
    default: ""
