fields:
  - type: section
    label: Allgemein
    cols: 1

  - key: extra_disks
    label: Zusätzlicher Speicher
    type: list
    description: "Mountpoints für zusätzliche Festplatten-Karten"
    mono: true
    default: []
